### PR TITLE
Update to current as of 2020-03-27

### PR DESCRIPTION
**Pull request by brianksorensen**
It looks like their default cache is Aerospike, but we are using Redis.  Do we need to do anything with the migration we are making to get away from Aerospike, or will we fit as implemented.

### CODE REVIEW

**Comment by vinnybod** [comment]
Hey @brianksorensen we should be good to go with the Aerospike/Redis change since they still support redis and we already have it configured in Ansible. One thing here though, we should do a merge from their fork. The way this is now, we aren't getting any of the commits so we 
1. Lose the history of all the chanages
2. Git will still see this as out of sync and will cause conflicts when trying to pull in changes again later

**Comment by brianksorensen** [comment]
> 1. Lose the history of all the changes
> 2. Git will still see this as out of sync and will cause conflicts when trying to pull in changes again later

#1 is exactly intentional.  It is basic configuration management theory, with the goal of keeping the contexts separate and encapsulated.  It is effectively doing the same as a merge with the fast forward strategy.  This is typically used in the git world to purify the merges in the master branch with respect to the specific changes in the development branch.  From a CM standpoint, you would never remove just one of the atomic changes made in development without generating a new release artifact.  In the master frame, you only care about the deltas that make up a specific release candidate, not all of the deltas the developers may have generated as they progressed toward their correct solution candidate.

#2.  The operation of merging the fork main into a derived branch does not provide the same result as what I have done.  To illustrate I have created two branches ENG-3985 and ENG-3985A, both derived from our current master.  The first, I did a pull request with changes moving from the Rubicon fork into that branch.  The second, I did a merge from the Rubicon fork's master branch after adding the Rubicon repository.  The to exactly match with respect to end result of the artifact files.  But neither match the file changes in the develop branch.  Some existing changes were completely dropped.  For example, in the log4j files, the existing:
        <Property name="fileName">${sys:log.dir}/spring-boot-service.log</Property>
was reset to the original
        <Property name="fileName">${sys:log.dir}/prebid-cache.log</Property> .

As opposed to the redis section in the application.xml was maintained.

The files with differences are:
/prebid-cache-java/src/main/java/org/prebid/cache/handlers/CacheHandler.java
/prebid-cache-java/src/main/resources/log4j2-console.xml
/prebid-cache-java/src/main/resources/log4j2-dev.xml
/prebid-cache-java/src/main/resources/log4j2-prod.xml
/prebid-cache-java/src/main/resources/log4j2-qa.xml

The CacheHandler difference is interesting as it highlights the problem I was having on prebid server with having log messages being arbitrarily dropped, which is what caused me to step back and do the contextual changes by hand, which highlighted other lines being dropped that would not have been easy to find when the fault manifested itself.

**Comment by vinnybod** [comment]
>In the master frame, you only care about the deltas that make up a specific release candidate, not all of the deltas the developers may have generated as they progressed toward their correct solution candidate.
This true up to a point and I am definitely a proponent of squashing a feature branch into master, but that's not the same situation here since we are trying to sync our fork with the main repository, and we don't want erase the REFs that git uses when we do another merge in the future. Since this will essentially make git think that those commits were never merged over in the first place.

I think this might come down to a misunderstanding of the underlying changes. For example:
```
${sys:log.dir}/spring-boot-service.log
was reset to the original
${sys:log.dir}/prebid-cache.log .
```

As far as I can tell `spring-boot-service.log` is the original and its been updated to` prebid-cache.log` which we would want no? If anything, you would resolve any conflicts like that in the merge commit.

ENG-3895A wasn't showing any diff, so i pushed up an example branch here of what I am proposing
https://github.com/freestarcapital/prebid-cache-java/compare/master...freestarcapital:vince-test

**Comment by maddapper** [comment]
So @vinnybod does have some valid points but I would say, go with the whatever convention that has already been established as that is more important than any particular git workflow.  As far as the code changes themselves, @brianksorensen PR looks correct as compared to the vinny:test branch.  I think this PR is fine as-is.

**Comment by brianksorensen** [comment]
@vinnybod, that is good pushback with respect to the dev branch, and I agree.  I actually came to that determination over my lunch break.
  The log file example kind of clouded the point, but also brings up another one.  Creating the log files in the pod environment is not helpful.  There you want your logs to go to the console so the output is available from the command line tools.  Log files on long running pods only uses up space, and as we learned from our SSP trial, can cause them to crash, and use far too much resource.
  The log control files do have the entry that selects the Console over the Filesystem, and that would have been lost.

So, here is my proposal.
  Initially I created a develop branch as my working branch.  I have a copy of the reference branch and I use my toolset to work through the deltas, resolving them on both sides, making sure the common reference between the two is what we want.
  Going forward, we will have a develop branch, that should match the last master branch at a release point.  It becomes my local reference point.  Rather than having a copy of the main fork master, I create my working branch from develop, and merge the main fork master into it.  This becomes my second reference point.  I can then resolve any deltas between my two reference points to make sure we don't drop any local changes that were made to support local business rules.

For now, I will resolve the delta for the ENG-3985 branch; remove and re-create the develop branch based on master, and create a pull request for the new change into develop.

How does that sound?  @vinnybod @maddapper   It will only take around five or ten minutes.

**Pull request closed without merging**
